on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  run_pr_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Run PR Agent CLI
        run: |
          docker run --rm \
            -v "$PWD":/github/workspace \
            -e IC_CODE_KEY="${{ secrets.API_KEY }}" \
            -e IC_CODE_BASE_URL="${{ secrets.BASE_URL }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            codingassistant/github_pr_agent:latest \
            python /github/workspace/pr_agent/cli.py
