on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PR Agent in Docker
        run: |
          docker run --rm \
            -v "$PWD":/github/workspace \
            -e IC_CODE_KEY="${{ secrets.API_KEY }}" \
            -e IC_CODE_BASE_URL="${{ secrets.BASE_URL }}" \
            -e GITHUB_USER_TOKEN="${{ secrets.MY_GITHUB_TOKEN }}" \
            codingassistant/github_pr_agent:github \
            python ./pr_agent/cli.py --pr_url="${{ github.event.pull_request.html_url }}" review
